<a href="https://colab.research.google.com/github/iamshubhamworkgit/Python-Project/blob/main/Loan_Status_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Installing dependencies

In [52]:
import pandas as pd

Importing dataset

In [53]:
data = pd.read_csv("/content/Loan status.csv")

###1. Top 5 Row'*s*

In [54]:
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

###2. Last 5 Row's

In [55]:
data.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

###3. Shape of dataset(No. of columns and rows)

In [56]:
data.shape

(614, 13)

In [57]:
print("Number of row's", data.shape[0])
print("Number of column's", data.shape[1])

Number of row's 614
Number of column's 13

###4. Information about dataset

In [58]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

Description of the dataset

In [59]:
data.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

###5. Checking Null Values

In [60]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

Null values in percentage

In [61]:
data.isnull().sum()/len(data)*100

Loan_ID              0.000000
Gender               2.117264
Married              0.488599
Dependents           2.442997
Education            0.000000
Self_Employed        5.211726
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           3.583062
Loan_Amount_Term     2.280130
Credit_History       8.143322
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

###6. Handling Null Values

In [62]:
data = data.drop("Loan_ID",axis = 1)

In [63]:
coloumn = ["Gender","Married","Dependents","LoanAmount","Loan_Amount_Term"]

In [64]:
data = data.dropna(subset =coloumn)

In [65]:
data.isnull().sum()/len(data)*100

Gender               0.000000
Married              0.000000
Dependents           0.000000
Education            0.000000
Self_Employed        5.424955
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           0.000000
Loan_Amount_Term     0.000000
Credit_History       8.679928
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [66]:
data["Self_Employed"].unique()

array(['No', 'Yes', nan], dtype=object)

In [67]:
data["Self_Employed"].mode()

0    No
Name: Self_Employed, dtype: object

In [68]:
data["Self_Employed"]= data["Self_Employed"].fillna('No')

In [69]:
data.isnull().sum()/len(data)*100

Gender               0.000000
Married              0.000000
Dependents           0.000000
Education            0.000000
Self_Employed        0.000000
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           0.000000
Loan_Amount_Term     0.000000
Credit_History       8.679928
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [70]:
data["Credit_History"].unique()

array([ 1.,  0., nan])

In [71]:
data["Credit_History"].mode()

0    1.0
Name: Credit_History, dtype: float64

In [72]:
data["Credit_History"]= data["Credit_History"].fillna(1.0)

In [73]:
data.isnull().sum()/len(data)*100

Gender               0.0
Married              0.0
Dependents           0.0
Education            0.0
Self_Employed        0.0
ApplicantIncome      0.0
CoapplicantIncome    0.0
LoanAmount           0.0
Loan_Amount_Term     0.0
Credit_History       0.0
Property_Area        0.0
Loan_Status          0.0
dtype: float64

###7. Handling Categorical Columns

In [74]:
data.sample(6)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
422,Male,Yes,0,Graduate,No,1820,1719.0,100.0,360.0,1.0,Urban,Y
544,Female,Yes,0,Not Graduate,No,3017,663.0,102.0,360.0,1.0,Semiurban,Y
352,Male,Yes,3+,Graduate,No,2666,2083.0,95.0,360.0,1.0,Rural,Y
570,Male,Yes,1,Graduate,No,3417,1750.0,186.0,360.0,1.0,Urban,Y
161,Male,Yes,0,Graduate,No,7933,0.0,275.0,360.0,1.0,Urban,N
545,Male,Yes,0,Graduate,No,2768,1950.0,155.0,360.0,1.0,Rural,Y

In [75]:
data["Dependents"].unique()

array(['1', '0', '2', '3+'], dtype=object)

In [76]:
data["Dependents"]= data["Dependents"].replace(to_replace= '3+', value= '4')

In [77]:
data["Dependents"].unique()

array(['1', '0', '2', '4'], dtype=object)

In [78]:
data["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [79]:
data["Gender"] = data["Gender"].map({"Male" : 1 , "Female" : 0}).astype(int)

In [80]:
data["Married"] = data["Married"].map({"Yes" : 1 , "No" : 0}).astype(int)
data["Education"] = data["Education"].map({"Graduate" : 1 , "Not Graduate" : 0}).astype(int)
data["Self_Employed"] = data["Self_Employed"].map({"Yes" : 1 , "No" : 0}).astype(int)
data["Property_Area"] = data["Property_Area"].map({"Rural" : 1 , "Urban" : 0 , "Semiurban" : 3}).astype(int)
data["Loan_Status"] = data["Loan_Status"].map({"Y" : 1 , "N" : 0}).astype(int)

In [81]:
data.sample(5)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
390,1,0,4,1,0,9167,0.0,185.0,360.0,1.0,1,1
58,1,1,1,1,0,8080,2250.0,180.0,360.0,1.0,0,1
561,0,1,1,1,1,19484,0.0,600.0,360.0,1.0,3,1
439,0,1,0,0,1,7142,0.0,138.0,360.0,1.0,1,1
125,0,0,0,1,0,3692,0.0,93.0,360.0,1.0,1,1

###8. Store Feature Matrix in X and Response(Target) in y

In [82]:
X = data.drop('Loan_Status', axis = 1)
y = data['Loan_Status']
y

1      0
2      1
3      1
4      1
5      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 553, dtype: int64

###9. Feature **Scaling**

In [83]:
data.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,1,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,0,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,0,1
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,0,1
5,1,1,2,1,1,5417,4196.0,267.0,360.0,1.0,0,1

In [84]:
cols = ['ApplicantIncome', 'CoapplicantIncome' , 'LoanAmount', 'Loan_Amount_Term' ]

In [85]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X[cols] = ss.fit_transform(X[cols])

In [86]:
X.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
1,1,1,1,1,0,-0.128694,-0.049699,-0.214368,0.279961,1.0,1
2,1,1,0,1,1,-0.394296,-0.545638,-0.952675,0.279961,1.0,0
3,1,1,0,0,0,-0.464262,0.229842,-0.309634,0.279961,1.0,0
4,1,0,0,1,0,0.109057,-0.545638,-0.059562,0.279961,1.0,0
5,1,1,2,1,1,0.011239,0.834309,1.440866,0.279961,1.0,0

###10. Splitting Dataset into Training Set and Testing Set

In [87]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [88]:
def model_val(model,X,y):
    X_train,X_test,y_train,y_test=train_test_split(X,y,
                                                   test_size=0.20,
                                                   random_state=42)
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    print(f"{model} accuracy is {accuracy_score(y_test,y_pred)}")

###11. Logistic Regression

In [89]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model_val(model,X,y)

LogisticRegression() accuracy is 0.8018018018018018

###12. SupportVectorClassifier (SVC)

In [90]:
from sklearn.svm import SVC
model = SVC()
model_val(model,X,y)

SVC() accuracy is 0.7927927927927928

###13. DecisionTreeClassifier

In [91]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model_val(model,X,y)

DecisionTreeClassifier() accuracy is 0.7117117117117117

###14. Train the best model on entier Dataset

In [92]:
X = data.drop('Loan_Status',axis=1)
y = data['Loan_Status']

In [93]:
lg = LogisticRegression()

In [94]:
lg.fit(X,y)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

###15. Save the Model

In [95]:
import joblib

In [96]:
joblib.dump(lg,'Loan_status_predict')

['Loan_status_predict']

###16. Load the saved model

In [97]:
model = joblib.load('Loan_status_predict')

###17. Perform prediction on unseen data

In [98]:
import pandas as pd
df = pd.DataFrame({
    'Gender':1,
    'Married':0,
    'Dependents':1,
    'Education':1,
    'Self_Employed':1,
    'ApplicantIncome':3569,
    'CoapplicantIncome':0.0,
    'LoanAmount':150,
    'Loan_Amount_Term':160,
    'Credit_History':1,
    'Property_Area':1
},index=[0])

In [99]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,1,0,1,1,1,3569,0.0,150,160,1,1

In [100]:
result = model.predict(df)

In [101]:
if result==1:
    print("Loan Approved")
else:
    print("Loan Not Approved")

Loan Approved